
<!-- chama o header primeiro -->
<?php require VIEWS_PATH . 'includes/header.phtml';?>

<!--Chama a main principal chamada "home" -->
<div class="container">
    
    <div class="col-md-12">

      <div class="col-md-6 text-left">
          <img src="http://via.placeholder.com/600x350?text=<?=$this->product['name'];?>" alt="" class="img-responsive">
      </div>

      <div class="col-md-6">
          <h2><a href="<?=HOME;?>/product/<?=$this->product['id'];?>"><?=$this->product['name'];?></a></h2>
          <p><?=$this->product['description'];?></p>
          <p>R$ <?=number_format($this->product['price'], 2, ',', '.');?></p>
          <!--                         decimals: 2, dec_point: ',', thousands_sep:'.');?></p> -->
      </div>
    
    </div>

</div> <!-- /container -->

<!-- chama o footer -->
<?php require VIEWS_PATH . 'includes/footer.phtml';?>